PRODUCT=iChatLegacyProbe
SRC=main.m
CFLAGS=-Wall -Wextra -mmacosx-version-min=10.6
FRAMEWORKS=-framework Foundation

all:
	$(CC) $(CFLAGS) $(SRC) -o $(PRODUCT) $(FRAMEWORKS)

clean:
	rm -f $(PRODUCT)
